# Extract configuration
# Enable interactive comments
setopt interactivecomments

# Enable auto cd
setopt auto_cd

# zmv
autoload -U zmv
alias zmv='noglob zmv'

source ~/.zsh/completion.zsh
source ~/.zsh/keybindings.zsh
source ~/.zsh/history.zsh
source ~/.zsh/clipboard.zsh
source ~/.zsh/functions.zsh
source ~/.zsh/aliases.zsh

# Load z if installed
if [[ -f ~/.zsh/plugins/z/z.sh ]]; then
    source ~/.zsh/plugins/z/z.sh
fi

# Load nvm if installed
export NVM_DIR="$HOME/.nvm"
if [[ -f "$NVM_DIR/nvm.sh" ]]; then
    # It seems `source nvm --no-use && nvm use default` is faster by a few milliseconds than just `source nvm.sh`.
    source "$NVM_DIR/nvm.sh" --no-use && nvm use default --silent

    if [[ -f "$NVM_DIR/bash_completion" ]]; then
        source "$NVM_DIR/bash_completion"
    fi
fi

export LC_ALL=en_GB.UTF-8
export LC_CTYPE=en_GB.UTF-8

export EDITOR=vim
export GIT_EDITOR=${EDITOR}

export PATH="${HOME}/go/bin:/usr/local/go/bin:$PATH"

[ -z "${MANPATH-}" ] || export MANPATH=":${MANPATH#:}";

# Register Homebrew paths
if [[ "$OSTYPE" == linux* ]]; then
    export HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew";
    export HOMEBREW_CELLAR="/home/linuxbrew/.linuxbrew/Cellar";
    export HOMEBREW_REPOSITORY="/home/linuxbrew/.linuxbrew/Homebrew";
elif [[ "$OSTYPE" == darwin* ]]; then
    export HOMEBREW_PREFIX="/opt/homebrew";
    export HOMEBREW_CELLAR="/opt/homebrew/Cellar";
    export HOMEBREW_REPOSITORY="/opt/homebrew";
fi

if [[ -n "$HOMEBREW_PREFIX" ]]; then
    fpath[1,0]="${HOMEBREW_PREFIX}/share/zsh/site-functions";
    export PATH="${HOMEBREW_PREFIX}/bin:${HOMEBREW_PREFIX}/sbin${PATH+:$PATH}";
    export INFOPATH="${HOMEBREW_PREFIX}/share/info:${INFOPATH:-}";
fi

if [[ "$OSTYPE" == darwin* ]]; then
    if [[ -d "/opt/homebrew/opt/curl" ]]; then
        export PATH="/opt/homebrew/opt/curl/bin:$PATH"
    fi

    if [[ -d "/Applications/Visual Studio Code.app" ]]; then
        export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
    fi
fi

export PATH="${HOME}/bin:${HOME}/.bin:${HOME}/.local/bin:${PATH}"

# Load local zshrc if available
if [[ -f ~/.zshrc.local ]]; then
    source ~/.zshrc.local
fi

# Load zsh-syntax-highlighting if installed
if [[ -f ~/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]]; then
    # Configuration for zsh-syntax-highlighting
    # TODO: Extract configuration
    ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern)
    ZSH_HIGHLIGHT_PATTERNS+=('rm -rf *' 'fg=white,bold,bg=red')

    source ~/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi

# Load the theme
source ~/.zsh/theme.zsh
